### ISSUE TITLE
Facebook Comments Plugin

### ISSUE THREAD

**Issue by mbtocalli** [AutoLoadNextPost/Auto-Load-Next-Post#139]
I'm using Facebook Comments Plugin to replace native Wordpress comments in my blog.
When using infinite scrol, Facebook Comments Plugin doesn't show. It seems that Facebook Comments Plugin script is fired on page load, but once the infinite scroll loads more markup, it doesn't get re-triggered. The FB.XFBML object has "parse" method, which will cause the tags to re-render into buttons.
How can I call this method (literally, it's just FB.XFBML.parse(); call) when the infinite scroll is done with loading the next fragment?

**Comment by seb86** [comment]
Sorry for the late response @mbtocalli

I received no notification as this is a developer's portal for Auto Load Next Post and should not be used for general support. Please visit the [support forum on WordPress.org](https://wordpress.org/support/plugin/auto-load-next-post) if you need help.
