### ISSUE TITLE
Welcome notice stops dashboard pages loading

### ISSUE THREAD

**Issue by seb86** [AutoLoadNextPost/Auto-Load-Next-Post#144]
A few reports have come in saying the dashboard is getting blocked once the plugin is activated and only the welcome notice shows. The welcome notice provides a dismiss link but according to the screenshot provided by a user, it is not showing.

![welcome-notice-crash](https://user-images.githubusercontent.com/497406/48015382-5160b080-e129-11e8-821b-1d32814ef303.jpg)

As I have not had this problem when installing ALNP on a fresh installation of WordPress I will label this issue as bug unconfirmed for now until I am able to reproduce this issue.

**Comment by mxmkmarquette** [comment]
i had the same problem, with the theme bimber.

i just delete your plugin by ftp, since it was already bundle in the theme.

**Comment by seb86** [comment]
It looks like it is related to the theme customizer.

**Comment by seb86** [comment]
I was right, it was to do with the customizer. I will be pushing an update shortly.

**Comment by seb86** [comment]
Pull request #145
