### ISSUE TITLE
Released version on W.org contains the plugin twice

### ISSUE THREAD

**Issue by Nikschavan** [autoloadnextpost/auto-load-next-post#170]
If you check the [SVN Repo](https://plugins.trac.wordpress.org/browser/auto-load-next-post/tags/1.5.14?order=name#trunk) the plugin is duplicated in the `/trunk` directory inside the release tag.

**Comment by Nikschavan** [comment]
Suggestion - You can use a [GitHub action](https://github.com/10up/action-wordpress-plugin-deploy) to deploy the plugin update from GitHub.

**Comment by seb86** [comment]
Error on my part for that release not my deploy script but thank you for the suggestion. Will clean it up for the next release. Thank you.
