### ISSUE TITLE
Next post is not loaded after submitting a comment then scrolling down the page

### ISSUE THREAD

**Issue by daveromsey** [autoloadnextpost/auto-load-next-post#172]
## Describe the bug

I've run into an issue where ALNP does not load the next post after submitting a comment and then scrolling down the page which has #comment-XX appended to the URL.

I believe this has to do with the page loading too far down and therefore past the previous/next post links which ALNP uses for loading the next post. Not sure about that exactly, but when I tested loading up URLs with anchors that were inside of the post (but at the bottom of it), ALNP still worked properly.

For troubleshooting, after submitting a comment, I tried scrolling up the page and then back down to try and get ALNP to do its thing, but that did not work.

## Prerequisites

- [X] I have searched the [documentation](https://github.com/autoloadnextpost/alnp-documentation/tree/master/en_US#the-manual) for answers and cannot find a solution.
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest `master` branch of Auto Load Next Post on GitHub (this is **not** the same version as on WordPress.org!)
- [X] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional)

## Steps to reproduce the issue

1. Post a comment
2. (WP reloads page with #comment-XX anchor appended to URL)
3. Scroll down
4. ALNP does not load the next post

If I load this same page without the comment anchor in the URL, the next post loads when scrolling down.

## Expected/actual behaviour

When I follow those steps I was expecting to see the next post loaded when scrolling down further, but this does not happen.

## Isolating the problem

- [X] This bug happens with only Auto Load Next Post plugin active.
- [X] This bug happens with a default WordPress theme active.
- [X] I can reproduce this bug consistently using the steps above.

## WordPress Environment
v5.3

**Comment by seb86** [comment]
This is expected behaviour so the visitor is able to read the comments of the post. [See here](https://github.com/autoloadnextpost/auto-load-next-post/blob/master/assets/js/frontend/auto-load-next-post.js#L76).

**Comment by daveromsey** [comment]
Thank you for your comment.

It would be nice if there were some way to override this feature (without manipulating the query args that WP adds). I'd like to keep ALNP active even when viewing or posting comments.
