### ISSUE TITLE
Auto load fails on href="javascript:void(0)"

### ISSUE THREAD

**Issue by Neoglyph** [AutoLoadNextPost/Auto-Load-Next-Post#87]
The javascript doesn't evaluate the href value as undefined, passing it through the `if ( !post_url ) return;` returning this:

`XMLHttpRequest cannot load javascript:void(0)/partial/. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.`

**Comment by seb86** [comment]
Why is the href not a URL?

**Comment by Neoglyph** [comment]
Wordpress theme specific - the theme inserts void where no link is available. 
Also this plugin takes the value of the rel="prev" button instead of the rel="next" button, which also makes me curious of why, but that is a question for another post.

I have tracked down the void code to: `$prev_output = sprintf( '<a href="%s" rel="prev">', 'javascript:void(0)' ) . $r['link_before'] . $r['previous_post_link'] . $r['link_after'] . '</a>';`

And while I can fix that, other users with not much technical knowledge could get stuck at this problem, that is why I have mentioned this as an issue.

**Comment by seb86** [comment]
This is not an issue with the plugin but an issue with the theme. This is not the standard way of adding a post navigation to a single post. Without knowing the post url the plugin can not know what post to load next.

**Comment by Aaronsinho** [comment]
Same problem with this theme https://themeforest.net/item/boombox-viral-buzz-wordpress-theme/16596434

**Comment by Aaronsinho** [comment]
This is the single post
``<?php`
/**
 * The template for displaying the single post
 *
 * @package BoomBox_Theme
 */

// Prevent direct script access.
if (!defined('ABSPATH')) {
    die('No direct script access allowed');
}

get_header();

$boombox_featured_image_size = 'boombox_image768';
$boombox_single_options = boombox_get_single_page_settings($boombox_featured_image_size);
$boombox_featured_video = $boombox_single_options['featured_video'];
$boombox_template_options = $boombox_single_options['template_options'];
$boombox_post_template = $boombox_single_options['post_template'];
$boombox_is_nsfw_post = $boombox_single_options['is_nsfw'];
$boombox_article_classes = $boombox_single_options['classes'];
$boombox_disable_strip = $boombox_single_options['disable_strip'];
$boombox_enable_sidebar = $boombox_single_options['enable_sidebar'];

if (!$boombox_disable_strip):
    get_template_part('template-parts/featured', 'strip');
endif;

boombox_the_advertisement('boombox-single-before-content', 'large');

if ('full-width' == $boombox_post_template && have_posts()): the_post();
    $boombox_fimage_style = '';
    if ( apply_filters( 'boombox/single/show_media', ( $boombox_template_options['media'] && boombox_has_post_thumbnail() && boombox_show_thumbail() ) ) ) :
        $thumbnail_size = 'full';
        $boombox_thumbnail_url = wp_get_attachment_image_src(get_post_thumbnail_id(), $thumbnail_size );
        $boombox_thumbnail_url = isset( $boombox_thumbnail_url[0] ) ? $boombox_thumbnail_url[0] : apply_filters( 'boombox/post-default-thumbnail', '', $thumbnail_size );
        $boombox_fimage_style = $boombox_thumbnail_url ? 'style="background-image: url(\'' . esc_url( $boombox_thumbnail_url ) . '\')"' : '';
    endif; ?>
    <div class="post-featured-image" <?php echo $boombox_fimage_style; ?>>
        <div class="content">
            
            <header class="entry-header">
                <?php get_template_part('template-parts/single/single', 'header'); ?>
            </header>
        </div>
    </div>
    <?php
    rewind_posts();
endif; ?>

<div class="container main-container">
    <div id="main" class="site-main" role="main">
        <?php if (have_posts()): the_post(); ?>

            <?php

                do_action( 'boombox/single/before-main-content' );

                get_template_part('template-parts/single/content');

                // If comments are open or we have at least one comment, load up the comment template.
                if (comments_open() || get_comments_number()) :
                    comments_template();
                endif;

                do_action( 'boombox_single_before_navigation' );

                boombox_the_advertisement('boombox-single-before-navigation', 'large');

                if ($boombox_template_options['navigation']) :
                    get_template_part('template-parts/single/navigation');
                endif;

                if ($boombox_template_options['subscribe_form']) :
                    boombox_mailchimp_form();
                endif;

                if ($boombox_template_options['floating_navbar']) :
                    get_template_part( 'template-parts/single/fixed', 'header' );
                endif;

                if( $boombox_template_options['side_navigation'] ) :
                    get_template_part( 'template-parts/single/fixed', 'navigation' );
                endif;

                if ('post' == get_post_type()):
                    get_template_part('template-parts/single/posts', 'related');

                    get_template_part('template-parts/single/posts', 'more-from');

                    get_template_part('template-parts/single/posts', 'dont-miss');
                endif;

                do_action( 'boombox/single/after-main-content' );

        endif; ?>


    </div>

    <?php if ('no-sidebar' != $boombox_post_template && $boombox_enable_sidebar):
        get_sidebar();
    endif; ?>
</div>

<?php get_footer(); ?>
`

**Comment by seb86** [comment]
@Aaronsinho Sorry but this issue is closed and yours is unrelated to it. If you are wanting [setup support](https://autoloadnextpost.com/product/setup-support/?attribute_theme-from=Themeforest.net) then I would be happy to provide it.
