### ISSUE TITLE
BUG -- Next post loads instantly

### ISSUE THREAD

**Issue by theopape** [autoloadnextpost/auto-load-next-post#89]
Please see attached screenshot. The next article loads in upon page load. To replicate please visit demo site and go to a single page. Creates issues with SEO and crawlers trying to interpret the webpage.
![screen shot 2017-07-05 at 16 37 49](https://user-images.githubusercontent.com/4234302/27872451-c236b3ea-61a0-11e7-9cd9-a24c6e62f5b6.png)

**Comment by seb86** [comment]
Can you tell me:
* What SEO plugin you are using?
* Which crawlers are showing issues?
* What theme and version are you using?

**Comment by theopape** [comment]
Hi seb,

Yoast, Google is showing issues - the main being that it doesn't know if it's an article or video, as both might appear on the same page. Theme is heavily customised but was originally Twenty Twelve. Seems that the same issue appears on your demo site...

**Comment by seb86** [comment]
Could you share what issues Google is telling you? What is your site url?

**Comment by theopape** [comment]
I have just implemented a bit of a hacky fix (attached).

[auto-load-next-post.js.zip](https://github.com/AutoLoadNextPost/Auto-Load-Next-Post/files/1125844/auto-load-next-post.js.zip)

**Comment by theopape** [comment]
Although would be better to write that condition in JS (haven't had time to correct), but attached my working file.

**Comment by theopape** [comment]
[auto-load-next-post.dev.fix.optimised.broken.js.zip](https://github.com/AutoLoadNextPost/Auto-Load-Next-Post/files/1125847/auto-load-next-post.dev.fix.optimised.broken.js.zip)

**Comment by theopape** [comment]
https://www.flickreel.com/

**Comment by theopape** [comment]
https://www.google.co.uk/search?q=spider-man+homecoming+review&oq=spider-man+homecoming+review&aqs=chrome..69i57j69i60l3.4360j0j4&sourceid=chrome&ie=UTF-8#q=flickreel - the issue becomes apparent when Google displays Top Stories - trailers should have video icon overlaid and reviews/written not (can't see a great example of the latter right now). But the issue in terms of SEO is that Google and other search engines will interpret this as one page, so SEO-wise that's poor.

**Comment by theopape** [comment]
Also, bear in mind that if you load two pages on initial load, the speed of the page load will be impacted negatively.

**Comment by seb86** [comment]
> https://www.google.co.uk/search?q=spider-man+homecoming+review&oq=spider-man+homecoming+review&aqs=chrome..69i57j69i60l3.4360j0j4&sourceid=chrome&ie=UTF-8#q=flickreel

This does not return Spiderman Homecoming Reviews. It thinks I am searching just **flickreel**.

I did not know Google or other crawlers scan the site with Javascript enabled. Your the first to report an SEO issue so this is new to me. It should and only identify the parent article.

Could you explain the change you made much more clearly after forking and pushing a request. I will then test it out and if looks good I will put out a fix update.

**Comment by seb86** [comment]
@theopape [Contributing instructions](https://github.com/AutoLoadNextPost/Auto-Load-Next-Post/blob/master/CONTRIBUTING.md).

**Comment by theopape** [comment]
Hi Seb, I'm not suggesting that you use that exact code. Just more to give you some clues for a potential fix. Basically your own code is triggering changeURL() within alnp_enter() and alnp_leave(), but if you call it on alnp_enter(), that's going to trigger changeURL(); which contains a call to auto_load_next_post() as soon as the page loads. So I've tried to avoid that by not calling alnp_enter() on the first <hr style="height: 0" class="post-divider initial-post-divider" ... I've added this initial-post-divider class so we can ignore this. Really, I think you would be better off not using scrollspy, as it seems too limited. I would suggest switching to https://github.com/stutrek/scrollMonitor or other, as then you could measure when the post-dividers are about to come into the window and load (scrolling down or up the page).

**Comment by theopape** [comment]
So Seb, please find attached a JS solution which extends your existing codebase. Basically the issue you have is that 'enter' will trigger as soon as the page loads, whereas 'leave' only triggers on scroll. I still think you should look to rewrite this with ScrollMonitor or something similar though. Another bug you have is that you are always triggering this next post to load - so even if you scroll down really far then back up, it will trigger it again when you scroll back down. You might also consider detecting scroll direction (down or up) and potentially removing an article from the DOM then re-adding it. But this might be overkill.
[Archive.zip](https://github.com/AutoLoadNextPost/Auto-Load-Next-Post/files/1126308/Archive.zip)

**Comment by seb86** [comment]
@theopape This is not the correct way to contribute to the project. Please read the [contribution instructions for how to push a PR](https://github.com/AutoLoadNextPost/Auto-Load-Next-Post/blob/master/CONTRIBUTING.md#how-to-submit-a-pr) and I would be happy to take a look and test it.

If you do not do this then I can not see the differences in the changes that you have made or comment.

Also, many months ago I had already started improving the JS for how the posts load so that it does not load so many posts as you scroll but I have been very busy with client work and other projects so it has put plugin development on hold temporarily.

If your code works as a temporary fix then I would release it on WP.org for all and credit you for the work.

Thank you for your understanding.

**Comment by theopape** [comment]
OK cool, done. Good to hear you're working on improvements - I know what you mean about not having much time.

**Comment by seb86** [comment]
So this prevents the next post from auto loading the next post when initially loading a post, correct?

So any crawler will see the post as is because they dont scroll down and the SEO issue will be fixed, correct?

**Comment by theopape** [comment]
Enter triggers as soon as the page loads. You will see this if you run you .dev.js script. Leave only triggers once scrolled. It's still not ideal, as you should really wait until closer to the bottom of current post - so you might calculate bottom minus viewport height or something. Then in reverse you would trigger the initial post URL once we pass the bottom. But that would be for a future iteration.

**Comment by theopape** [comment]
Still not sure how crawlers will interpret as Google can even scroll the page I'm assuming.

**Comment by theopape** [comment]
It would appear that this has fixed the issues with Google/crawlers. There was another issue actually: if you had an article with an author, such as a review, Google would sometimes incorrectly attribute the article to the author of the next post. That looks like it has been fixed too.

**Comment by seb86** [comment]
I see. So your posts are reviews. That explains it. The plugin was not designed for reviews scheme markup so thats why you had an issue with Google.

**Comment by theopape** [comment]
Nope, any post type will have issues as you're loading in two posts at the same time. i.e. Google/search engines will read the page as having 2* H1 tags, etc.

**Comment by seb86** [comment]
So should I convert all posts headings from H1 to H2 for all posts after the initial post?

**Comment by theopape** [comment]
No that would be incorrect. All I'm saying is that this fix rectifies the issue, as we are no longer loading in two posts on the initial load (as the initial enter isn't called).

**Comment by seb86** [comment]
OK. I understand now. Not sure when I will get an update released yet. I'm very busy with another premium plugin at the moment.

**Comment by theopape** [comment]
No worries. Glad that makes sense.
