### ISSUE TITLE
Post Limiter

### ISSUE THREAD

**Issue by saeedrm6** [AutoLoadNextPost/Auto-Load-Next-Post#91]
Hello
How can I limit posts view?
I want to limit posts to 5 post after the post view, I try to set counter with add_action( 'alnp_load_before_loop', post_limiter($count));
I set $count=0 before while loop in content-partial.php and $count++ before while loop end...
but in vardump my counter variable just return 1; !!!!

in function.php of theme :
function post_limiter($counter){
    $counter++;
    var_dump($counter);
    return $counter;
}
add_action( 'alnp_load_before_content', 'post_limiter' );

**Comment by seb86** [comment]
@saeedrm6 Use [this](https://gist.github.com/seb86/520ec9840cf731bd3f3d6de9a71c233a).

**Comment by saeedrm6** [comment]
@seb86 thank you so much, its work
