### ISSUE TITLE
Load next and prev from category ID

### ISSUE THREAD

**Issue by saeedrm6** [AutoLoadNextPost/Auto-Load-Next-Post#93]
Hi
I use Yoast SEO and my posts may have more than 2 category, With YOAST I set my primary Category.
in the single.php I have navigation post to show next and prev post and your awesome plugin load next and prev post from this nav.
is there a way to load next posts from category ID?

**Comment by seb86** [comment]
@saeedrm6 Please [create a support ticket](https://wordpress.org/support/plugin/auto-load-next-post). This repository for bug reports and contributions only - if you have a support question or a request for a customisation this is not the right place to post it. Use [WordPress.org for community support](https://wordpress.org/support/plugin/auto-load-next-post). Thank you.
