### ISSUE TITLE
The back button is usless. 😞

### ISSUE THREAD

**Issue by seb86** [AutoLoadNextPost/Auto-Load-Next-Post#95]
It has been brought to my attention by [Rosella Celina](https://profiles.wordpress.org/rosellecelina) on [WordPress.org support forum](https://wordpress.org/support/topic/back-button-doesnt-go-to-the-top-of-the-last-post) that pressing the back button on your browser does not scroll up to the previous post.

[Video](https://youtu.be/SZpIjXqkv3o) demonstrating the 🐛 

I was unaware of this bug due to the fact the plugin was designed for users not to press the back button but it should still at least scroll back to the previous post which it does only instead it scrolls to the very end of the last post with another post in view and not the beginning of the post.

Additional Javascript will be needed to support this properly so this is the checklist.

### The Checklist
- [ ] Check history state that the previous post matches before scrolling back up to the beginning of that post.
- [ ] Animate the scroll for a smooth transition within 600 milliseconds.
- [ ] If no further previous posts found then just go back as normal.

**Comment by seb86** [comment]
Created [a snippet](https://gist.github.com/seb86/8d6bbbdfd010c6ac5d572cbd4dba1e5d) to test.

**Comment by seb86** [comment]
Snippet may require the use of another Javascript library that detects the back button being pressed. Which means if used will be another script to load.

New possible library: https://github.com/ianrogren/jquery-backDetect

**Comment by seb86** [comment]
For those who are wanting to complete this issue for the **Hacktoberfest** please [edit the developer version](https://github.com/AutoLoadNextPost/Auto-Load-Next-Post/blob/master/assets/js/frontend/auto-load-next-post.dev.js) of the frontend Javascript once you have forked the repository. Please [read the contributing guidelines](https://github.com/AutoLoadNextPost/Auto-Load-Next-Post/blob/master/CONTRIBUTING.md) fully.

Push requests that get merged from a contributor will be credited so please provide your WordPress.org username when pushing your contribution. Thank you and have fun hacking.

**Comment by lex111** [comment]
@seb86 assign to me please.

**Comment by seb86** [comment]
@lex111 I am unable to. Suggestions?

**Comment by lex111** [comment]
I was wrong, to assign it is necessary to have the repository permissions or to join the organization. I initially thought that you can assign any user.

**Comment by lex111** [comment]
@seb86 I joined the organization, now try to assign.

**Comment by seb86** [comment]
@lex111 It works.

**Comment by seb86** [comment]
Hi @lex111 

I am finally getting round to push a new release which includes your back button fix, however, I noticed that it removes the ability to go back forward.

Would it be possible for you to adapt it for me?

I have created a new issue and assigned you to it.

**Comment by lex111** [comment]
Hi Sébastien.

All right, I'll try to figure out this problem ASAP.

**Comment by seb86** [comment]
Thank you.
